// Satu sumber kebenaran untuk form vendor DAN tampilan admin. Ubah field di sini saja.
const F = (k, l, t = 'text', o = {}) => ({ k, l, t, ...o });
const DAYS = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu'];
const CATS = ['Tennis', 'Badminton', 'Gym', 'Pilates', 'Yoga', 'Fisioterapi', 'Massage/Spa', 'Lainnya'];
const IMG = 'image/*', DOC = '.pdf,image/*';

const SCHEMA = [
  { id: 'A', title: 'Informasi bisnis', f: [
    F('vid', 'Vendor ID', 'auto', { v: () => CODE }),
    F('date', 'Tanggal pendaftaran', 'auto', { v: () => new Date().toLocaleDateString('id-ID') }),
    F('brand', 'Nama brand / usaha', 'text', { req: 1 }),
    F('legal', 'Nama legal perusahaan / pemilik', 'text', { req: 1 }),
    F('type', 'Bentuk usaha', 'select', { req: 1, o: ['PT', 'CV', 'Perorangan', 'Lainnya'] }),
    F('type_other', 'Bentuk usaha lainnya', 'text', { show: ['type', 'Lainnya'], req: 1 }),
    F('cat', 'Kategori bisnis', 'select', { req: 1, o: CATS }),
    F('cat_other', 'Kategori lainnya', 'text', { show: ['cat', 'Lainnya'], req: 1 }),
    F('desc', 'Deskripsi usaha', 'textarea', { req: 1 }),
    F('web', 'Website', 'url'), F('ig', 'Instagram'), F('tt', 'TikTok'),
    F('year', 'Tahun berdiri', 'number', { min: 1900, max: 2100 }),
    F('pic', 'Nama PIC', 'text', { req: 1 }), F('role', 'Jabatan PIC'),
    F('wa', 'WhatsApp', 'tel', { req: 1 }), F('email', 'Email', 'email', { req: 1 }),
  ] },
  { id: 'B', title: 'Legal & verifikasi', f: [
    F('nib', 'NIB (PDF/gambar, maks 500 KB)', 'file', { req: 1, kb: 500, acc: DOC }),
    F('npwp', 'NPWP (PDF/gambar, maks 500 KB)', 'file', { req: 1, kb: 500, acc: DOC }),
    F('ktp', 'KTP pihak berwenang (gambar, maks 500 KB)', 'file', { req: 1, kb: 500, acc: IMG }),
    F('akta', 'Akta perusahaan (jika badan usaha, maks 1 MB)', 'file', { kb: 1000, acc: DOC }),
    F('izin', 'Izin operasional / profesi sesuai layanan (maks 1 MB)', 'file', { kb: 1000, acc: DOC }),
    F('izin_exp', 'Tanggal kedaluwarsa izin', 'date'),
    F('extra_name', 'Nama dokumen tambahan'),
    F('extra', 'Dokumen tambahan (maks 1 MB)', 'file', { kb: 1000, acc: DOC }),
    F('extra_exp', 'Tanggal kedaluwarsa dokumen tambahan', 'date'),
  ] },
  { id: 'C', title: 'Outlet / cabang', rep: 1, item: 'Outlet', add: 'Tambah outlet lain', f: [
    F('name', 'Nama outlet', 'text', { req: 1 }),
    F('addr', 'Alamat lengkap', 'textarea', { req: 1 }),
    F('maps', 'Tautan Google Maps', 'url', { req: 1 }),
    F('phone', 'Kontak outlet', 'tel', { req: 1 }),
    F('hours', 'Jam operasional per hari', 'hours'),
    F('fac', 'Fasilitas', 'checks', { o: ['Parkir', 'Shower', 'Locker', 'Towel', 'Wi-Fi', 'Changing room'] }),
    F('instr', 'Instruksi lokasi', 'textarea'),
    F('logo', 'Logo (gambar, maks 500 KB)', 'file', { kb: 500, acc: IMG }),
    F('gallery', 'Galeri foto & video (link Google Drive)', 'url'),
  ] },
  { id: 'D', title: 'Layanan / kelas', rep: 1, item: 'Layanan', add: 'Tambah layanan', f: [
    F('name', 'Nama layanan', 'text', { req: 1 }),
    F('cat', 'Kategori layanan', 'select', { req: 1, o: CATS }),
    F('outlet', 'Outlet penyedia', 'select', { req: 1, o: 'C.name' }),
    F('desc', 'Deskripsi layanan', 'textarea', { req: 1 }),
    F('dur', 'Durasi (menit)', 'number', { req: 1, min: 0 }),
    F('cap', 'Kapasitas maksimal', 'number', { min: 0 }),
    F('minp', 'Minimal peserta', 'number', { min: 0 }),
    F('prep', 'Persiapan pelanggan', 'textarea'),
    F('incl', 'Fasilitas termasuk', 'textarea'),
    F('limit', 'Batas usia / level / pembatasan', 'textarea'),
    F('retail', 'Harga retail (Rp)', 'number', { req: 1, min: 0 }),
    F('price', 'Harga jual ZenAja (Rp)', 'number', { req: 1, min: 0 }),
    F('special', 'Ketentuan pemesanan khusus', 'textarea'),
  ] },
  { id: 'E', title: 'Jadwal & ketersediaan', rep: 1, item: 'Jadwal', add: 'Tambah jadwal', f: [
    F('service', 'Layanan', 'select', { req: 1, o: 'D.name' }),
    F('days', 'Hari berulang', 'checks', { req: 1, o: DAYS }),
    F('start', 'Waktu mulai', 'time', { req: 1 }), F('end', 'Waktu selesai', 'time', { req: 1 }),
    F('staff', 'Instruktur / therapist'),
    F('cap', 'Kapasitas total', 'number', { min: 0 }), F('quota', 'Kuota ZenAja', 'number', { min: 0 }),
    F('blackout', 'Blackout date / hari libur / penutupan sementara', 'textarea'),
    F('early', 'Pemesanan paling awal (hari sebelum jadwal)', 'number', { min: 0 }),
    F('late', 'Pemesanan paling akhir (jam sebelum jadwal)', 'number', { min: 0 }),
  ] },
  { id: 'F', title: 'Staff / instruktur / therapist', rep: 1, item: 'Staff', add: 'Tambah staff', note: 'Lewati jika tidak relevan.', f: [
    F('name', 'Nama'), F('pos', 'Posisi'),
    F('photo', 'Foto (maks 500 KB)', 'file', { kb: 500, acc: IMG }),
    F('bio', 'Biodata singkat', 'textarea'),
    F('spec', 'Spesialisasi'), F('cert', 'Sertifikasi', 'textarea'), F('exp', 'Pengalaman'),
    F('services', 'Layanan yang ditangani', 'checks', { o: 'D.name' }),
    F('outlet', 'Outlet', 'select', { o: 'C.name' }),
    F('sched', 'Jadwal', 'textarea'),
  ] },
  { id: 'G', title: 'Kebijakan booking & pembatalan', f: [
    F('free_h', 'Batas pembatalan gratis (jam sebelum jadwal)', 'number', { def: 6, min: 0 }),
    F('lt6', 'Aturan pembatalan kurang dari batas gratis', 'textarea'),
    F('noshow', 'No-show dan keterlambatan', 'textarea'),
    F('resched', 'Aturan reschedule', 'textarea'),
    F('vcancel', 'Pembatalan oleh vendor, refund, penggantian jadwal', 'textarea'),
    F('exc', 'Pengecualian kebijakan yang perlu disetujui ZenAja', 'textarea'),
  ] },
  { id: 'H', title: 'Keuangan & bank', f: [
    F('bank', 'Nama bank', 'text', { req: 1 }), F('accno', 'Nomor rekening', 'text', { req: 1 }),
    F('accname', 'Nama pemilik rekening', 'text', { req: 1 }),
    F('proof', 'Bukti kepemilikan rekening (maks 1 MB)', 'file', { req: 1, kb: 1000, acc: DOC }),
    F('comm', 'Persentase komisi yang diusulkan (%)', 'number', { min: 0, max: 100 }),
    F('pgfee', 'Payment gateway fee'), F('fees', 'Biaya lainnya'),
    F('payout', 'Jadwal pencairan dana', 'select', { o: ['Mingguan', 'Dua mingguan', 'Bulanan', 'Lainnya'] }),
  ] },
  { id: 'I', title: 'Promosi & marketing', f: [
    F('promo', 'Persetujuan jenis promo', 'checks', { o: ['Promo pengguna baru', 'Voucher', 'Flash sale', 'Seasonal'] }),
    F('maxdisc', 'Diskon maksimum yang disetujui (%)', 'number', { min: 0, max: 100 }),
    F('collab', 'Minat kerja sama', 'checks', { o: ['KOL', 'Bundling', 'Membership'] }),
    F('assets', 'Saya mengizinkan ZenAja memakai logo, foto, dan materi pemasaran kami', 'check'),
  ] },
  { id: 'J', title: 'Iklan', f: [
    F('ads', 'Minat pemasangan iklan', 'checks', { o: ['Homepage Banner', 'Featured Vendor', 'Featured Class', 'Search Priority', 'Pop-up', 'Category Banner'] }),
    F('adcontact', 'Kontak untuk iklan'), F('budget', 'Budget iklan (Rp, opsional)', 'number', { min: 0 }),
  ] },
  { id: 'K', title: 'Akun admin vendor', rep: 1, item: 'Akun', add: 'Tambah akun pengguna lain', note: 'Akun pertama adalah admin utama.', f: [
    F('name', 'Nama', 'text', { req: 1 }), F('email', 'Email', 'email', { req: 1 }), F('phone', 'Nomor HP', 'tel', { req: 1 }),
    F('perm', 'Hak akses', 'checks', { o: ['Booking', 'Jadwal', 'Harga', 'Layanan', 'Staf', 'Laporan', 'Promo'] }),
    F('outlets', 'Outlet yang dapat diakses', 'checks', { o: 'C.name' }),
  ] },
  { id: 'L', title: 'Persetujuan & tanda tangan', f: [
    F('c1', 'Saya menyatakan seluruh data yang diisi benar', 'check', { req: 1 }),
    F('c2', 'Saya menyetujui Vendor Agreement', 'check', { req: 1 }),
    F('c3', 'Saya menyetujui ketentuan komisi dan payout', 'check', { req: 1 }),
    F('c4', 'Saya menyetujui ketentuan cancellation dan refund', 'check', { req: 1 }),
    F('c5', 'Saya menyetujui Privacy Policy dan penggunaan data', 'check', { req: 1 }),
    F('c6', 'Saya bersedia menerima informasi pemasaran ZenAja (opsional)', 'check'),
    F('signer', 'Nama penandatangan', 'text', { req: 1 }), F('srole', 'Jabatan', 'text', { req: 1 }),
    F('sdate', 'Tanggal', 'date', { req: 1, def: new Date().toISOString().slice(0, 10) }),
    F('sig', 'Tanda tangan digital (coret di area bawah)', 'sig', { req: 1 }),
  ] },
];
